### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by RoyceRemix** [Sididi/twitch-top-clippers#2]
Hi there!  I'm really interested in using this tool, does it still work? ( i ask since the power clipper feature seems to be long gone on Twitch as far as I know )  Thanks for making this!

**Comment by RoyceRemix** [comment]
Works fine!  One note, you may want to mention in the readme that the broadcaster ID also needs to be updated in the index.js file.  Thanks again for this tool!

**Comment by Sididi** [comment]
@RoyceRemix Sorry for the late answer, glad you made it work!
I've updated the readme
